### ISSUE TITLE
Issue on reproducing the BotRGCN results

### ISSUE THREAD

**Issue by 1001b** [LuoUndergradXJTU/TwiBot-22#1]
Hi, I couldn't run the preprocessing step in BotRGCN.  Here's the line of interest:
[https://github.com/LuoUndergradXJTU/TwiBot-22/blame/master/src/BotRGCN/twibot_22/preprocess_2.py#L52](url)

And what's the recommendation to merge all the tweets json files?

Cheers, JL

**Comment by BunsenFeng** [comment]
Thank you for your interest in our work! Tagging my colleague to help you @TamSiuhin

**Comment by leopoldwhite** [comment]
> Hi, I couldn't run the preprocessing step in BotRGCN. Here's the line of interest: [https://github.com/LuoUndergradXJTU/TwiBot-22/blame/master/src/BotRGCN/twibot_22/preprocess_2.py#L52](url)
> 
> And what's the recommendation to merge all the tweets json files?
> 
> Cheers, JL

Hi @1001b , We feel sorry for the confusion caused by our oversight. There're  some errors in our code and now they've been fixed. 

In [https://github.com/LuoUndergradXJTU/TwiBot-22/blob/master/src/BotRGCN/twibot_22/preprocess_1.py](https://github.com/LuoUndergradXJTU/TwiBot-22/blob/master/src/BotRGCN/twibot_22/preprocess_1.py). we add the code to process _edge.csv_. Also we add the code to merge all the tweets json files into _id_tweet.json_, which is a is a dict with user index (the same index in _user.json_) as key and all corresponding tweet texts as values. Then _id_tweet.json_ can be used in [https://github.com/LuoUndergradXJTU/TwiBot-22/blob/master/src/BotRGCN/twibot_22/preprocess_2.py](https://github.com/LuoUndergradXJTU/TwiBot-22/blob/master/src/BotRGCN/twibot_22/preprocess_2.py) to extract tweet_feature.

Again, we apologize for any inconvenience caused. We also thank you for helping us to find the problems. Hope this can help you.

**Comment by 1001b** [comment]
Hi leo, thanks for the correction.  There's also an issue with twibot-20 preprocessing code, https://github.com/LuoUndergradXJTU/TwiBot-22/blob/7d9f9c3f21d4fcd55cbb590c4b71c9d01beae0d5/src/BotRGCN/twibot_20/preprocess_2.py#L51.  "each_user_tweets" is undefined.  Thx.  JL

**Comment by leopoldwhite** [comment]
> Hi leo, thanks for the correction. There's also an issue with twibot-20 preprocessing code,
> 
> https://github.com/LuoUndergradXJTU/TwiBot-22/blob/7d9f9c3f21d4fcd55cbb590c4b71c9d01beae0d5/src/BotRGCN/twibot_20/preprocess_2.py#L51
> 
> . "each_user_tweets" is undefined. Thx. JL

Hi @1001b, now the code to get  _each_user_tweets_ is added in preprocess_1.py.
https://github.com/LuoUndergradXJTU/TwiBot-22/blob/f82dbb7894ae09e3b469570db155dfb8462309cf/src/BotRGCN/twibot_20/preprocess_1.py#L184

 Then _each_user_tweets_ can be used in preprocess_2.py.
https://github.com/LuoUndergradXJTU/TwiBot-22/blob/f82dbb7894ae09e3b469570db155dfb8462309cf/src/BotRGCN/twibot_20/preprocess_2.py#L12

**Comment by 1001b** [comment]
Thanks for the quick response, Leo.  On preprocess_1.py in twibot-22, the code seems to be expect 10 of the tweet_x.json files from (tweet_0 to tweet_9).  Is it missing tweet_9?  Or the range(10) should be range(9)?  Please advise.

**Comment by leopoldwhite** [comment]
> Thanks for the quick response, Leo. On preprocess_1.py in twibot-22, the code seems to be expecting 10 of the tweet_x.json files from (tweet_0 to tweet_9). Is it missing tweet_9 in the G drive? Or the range(10) should be range(9)? Please advise.

It should be range(9). Code has been updated.

https://github.com/LuoUndergradXJTU/TwiBot-22/blob/cc0034ad4f9d1863a41f6bbb2f66771e113f4a03/src/BotRGCN/twibot_22/preprocess_1.py#L197
