### ISSUE TITLE
About Roberta Finetune?

### ISSUE THREAD

**Issue by MMMMMz** [LuoUndergradXJTU/TwiBot-22#14]
When you run Roberta's code, is there no fine-tuning done in the feature processing?

**Comment by BunsenFeng** [comment]
Yes. We use pre-trained "roberta-base" from the transformers library for feature extraction and MLP layers for classification. We did not employ fine-tuning since we do not have enough computational resources for all tweets in TwiBot-22.

If you want to, you can easily fine-tune LMs on TwiBot-22 and we are looking forward to your results! :)
